"""add news

Revision ID: fd5e750f7ad5
Revises: 0c31efbc54b1
Create Date: 2022-06-12 14:59:23.657278

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'fd5e750f7ad5'
down_revision = '0c31efbc54b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('news_image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('news_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('news_id')
    )
    op.create_index(op.f('ix_news_news_date'), 'news', ['news_date'], unique=False)
    op.create_index(op.f('ix_news_news_image'), 'news', ['news_image'], unique=False)
    op.create_index(op.f('ix_news_title'), 'news', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_title'), table_name='news')
    op.drop_index(op.f('ix_news_news_image'), table_name='news')
    op.drop_index(op.f('ix_news_news_date'), table_name='news')
    op.drop_table('news')
    # ### end Alembic commands ###
